FROM php:7.4-fpm
RUN apt-get update
#RUN apt-get -y install libzip-dev
#RUN docker-php-ext-install pdo_mysql mysqli

#COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# php7.2以下のcomposer2.2.17
# COPY --from=composer:2.2.17 /usr/bin/composer /usr/bin/composer
