version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      app_net:
        ipv4_address: 172.24.0.2
    ports:
      - 80:80
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
      - ./code:/var/www/html/code
      - ../project/:/var/www/html/project
    depends_on:
      - php
      - php5.6
      - php7.4
      - node

  node:
    #image: node:latest
    build: ./containers/node
    container_name: node
    environment:
      - NODE_ENV=development
    volumes:
      - ./code/node:/usr/src/app
    networks:
      app_net:
        ipv4_address: 172.24.0.11
    ports:
      - 3000:3000
    #working_dir: /usr/src/app
    tty: true
    #command: "nodejs /usr/src/app/app.js"
    #command: "nodemon /usr/src/app/app.js"
    #command: bash -c "npm install && npm install nodemon -g && nodemon /usr/src/app/app.js"

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.24.0.0/24
