version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      app_net:
        ipv4_address: 172.24.0.2
    ports:
      - 80:80
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
      - ./code:/var/www/html/code

  php7.4:
    build:
      context: ./containers/php
      dockerfile: Dockerfile.php7.4
    container_name: php7.4-apache
    ports:
      - 81:81
      - 82:82
    volumes:
      - ./containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./containers/httpd/conf.d/vhost-php7.4.conf:/etc/apache2/sites-enabled/vhost-php.conf
      - ./code/php/:/var/www/html/code/php
    networks:
      app_net:
        ipv4_address: 172.24.0.3
    tty: true

  php8.2:
    build:
      context: ./containers/php
      dockerfile: Dockerfile.php8.2
    container_name: php8.2-apache
    ports:
      - 83:83
      - 84:84
    volumes:
      - ./containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./containers/httpd/conf.d/vhost-php8.2.conf:/etc/apache2/sites-enabled/vhost-php.conf
      - ./code/php/:/var/www/html/code/php
    networks:
      app_net:
        ipv4_address: 172.24.0.4
    tty: true

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.24.0.0/24
