version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      app_net:
        ipv4_address: 172.24.4.2
    ports:
      - 80:80
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
      - ./code:/var/www/html/code
      - ../project/:/var/www/html/project
    depends_on:
      - php
      - php5.6
      - php7.4

  php:
    build: ./containers/php
    container_name: php
    volumes:
      - ./containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./containers/php/conf.d/fakemail.ini:/usr/local/etc/php/conf.d/fakemail.ini
      - ./code/php:/var/www/html/code/php
      - ../project/:/var/www/html/project
    networks:
      app_net:
        ipv4_address: 172.24.4.5
    extra_hosts:
      - "api.local.mysite.test:172.24.0.21"
    tty: true
    depends_on:
      - mysql
    links:
      - mysql
      - fakemail
      - redis

  php5.6:
    build:
      context: ./containers/php
      dockerfile: Dockerfile.php5.6
    container_name: php5.6
    volumes:
      - ./containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./code/php/php5.6:/var/www/html/code/php/php5.6
    networks:
      app_net:
        ipv4_address: 172.24.4.6
    tty: true
    links:
      - mysql
      - fakemail
      - redis

  php7.4:
    build:
      context: ./containers/php
      dockerfile: Dockerfile.php7.4
    container_name: php7.4
    volumes:
      - ./containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./code/php/php7.4:/var/www/html/code/php/php7.4
    networks:
      app_net:
        ipv4_address: 172.24.4.7
    tty: true
    links:
      - mysql
      - fakemail
      - redis

  node:
    #image: node:latest
    build: ./containers/node
    container_name: node
    environment:
      - NODE_ENV=development
    volumes:
      - ./code/node:/usr/src/app
    networks:
      app_net:
        ipv4_address: 172.24.4.11
    ports:
      - 3000:3000
    #working_dir: /usr/src/app
    tty: true
    #command: "nodejs /usr/src/app/app.js"
    #command: "nodemon /usr/src/app/app.js"
    #command: bash -c "npm install && npm install nodemon -g && nodemon /usr/src/app/app.js"

  redis:
    image: "redis:latest"
    container_name: redis
    networks:
      app_net:
        ipv4_address: 172.24.4.13
    ports:
      - "6379:6379"
    volumes:
      - /vagrant/docker-data/redis/data:/data

  mysql:
    image: mariadb:10.11
    container_name: mysql
    volumes:
      - ./containers/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./containers/mysql/scripts:/docker-entrypoint-initdb.d
      - /vagrant/docker-data/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysite
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      app_net:
        ipv4_address: 172.24.4.14
    ports:
      - 3306:3306

  fakemail:
    image: mailhog/mailhog:latest
    #image: axllent/mailpit:latest
    container_name: fakemail
    tty: true
    networks:
      app_net:
        ipv4_address: 172.24.4.15
    ports:
      - "8025:8025"
      - "1025:1025"
    #environment:
    #  MP_DATA_FILE: /home/mailpit/mails
    #  MP_SMTP_SSL_CERT: /keys/cert.pem #これを追加
    #  MP_SMTP_SSL_KEY: /keys/privkey.pem #これを追加
    # volumes:
    #  - /vagrant/docker-data/mailpit:/home/mailpit/mails

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.24.4.0/24
