version: '3'
services:
  httpd:
    image: httpd:latest
    container_name: httpd
    networks:
      app_net:
        ipv4_address: 172.24.0.2
    ports:
      - 80:80
    volumes:
      - ./containers/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./containers/httpd/conf.d/vhost-php7.4.conf:/usr/local/apache2/conf/vhosts/vhost-php7.4.conf
      - ./containers/httpd/conf.d/vhost-php8.2.conf:/usr/local/apache2/conf/vhosts/vhost-php8.2.conf
      - ./code:/var/www/html/code
    depends_on:
      - php7.4
      - php8.2

  php7.4:
    build:
      context: ./containers/php
      dockerfile: Dockerfile.php7.4
    container_name: php7.4-fpm
    volumes:
      - ./containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./code/php/:/var/www/html/code/php
    networks:
      app_net:
        ipv4_address: 172.24.0.3
    tty: true

  php8.2:
    build:
      context: ./containers/php
      dockerfile: Dockerfile.php8.2
    container_name: php8.2-fpm
    volumes:
      - ./containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./code/php/:/var/www/html/code/php
    networks:
      app_net:
        ipv4_address: 172.24.0.4
    tty: true

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.24.0.0/24
